import type { CSSProperties } from "react";
import { operatorUiColors as U } from "@/lib/themes/Colors";

export const styles: Record<string, CSSProperties> = {
  root: {
    height: 52,
    background: U.surface,
    borderBottom: `1px solid ${U.border}`,
    display: "flex",
    alignItems: "center",
    padding: "0 24px",
    justifyContent: "space-between",
    flexShrink: 0,
  },
  left: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  title: {
    fontSize: 16,
    fontWeight: 700,
    color: U.text,
  },
  subtitle: {
    fontSize: 12,
    color: U.textTer,
  },
  right: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  periodSelect: {
    fontSize: 12,
    padding: "6px 10px",
    borderRadius: 6,
    border: `1px solid ${U.border}`,
    background: U.surface,
    color: U.text,
    cursor: "pointer",
    fontWeight: 500,
    fontFamily: "inherit",
  },
  btnPrimary: {
    fontSize: 12,
    padding: "6px 12px",
    borderRadius: 6,
    border: "none",
    background: U.primary,
    color: "#fff",
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontFamily: "inherit",
  },
  btnOutline: {
    fontSize: 12,
    padding: "6px 12px",
    borderRadius: 6,
    border: `1px solid ${U.border}`,
    background: U.surface,
    color: U.textSec,
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontFamily: "inherit",
  },
};
