"""Report emergency use case module.
This module defines the command and handler for reporting emergencies in the system.
It coordinates between storage and coordination services to process emergency reports.
"""

from datetime import datetime

import cqrs

from core.domain.entities.emergency import Emergency
from core.domain.value_objects.location import Location
from core.domain.value_objects.medical_info import MedicalInfo

from ..ports.coordinator import CoordinatorPort
from ..ports.realtime_storage import RealTimeStoragePort


class ReportEmergencyCommand(cqrs.Request):
    """Command for reporting an emergency.

    This command contains the necessary information to report an emergency,
    including location and optional medical information.

    Attributes:
        location: The location where the emergency occurred.
        medicalInfo: Optional medical information related to the emergency.
    """

    location: Location
    medicalInfo: MedicalInfo | None
    createdOn: datetime

    def to_domain(self) -> Emergency:
        """Converts the command to a domain Emergency entity.

        Returns:
            An Emergency entity initialized with the command's data
        """
        return Emergency(self.location, self.createdOn, self.medicalInfo)


class ReportEmergencyHandler(cqrs.RequestHandler[ReportEmergencyCommand, None]):
    """Handler for processing ReportEmergencyCommand.

    This handler coordinates the storage and reporting of emergency information
    by delegating through the appropriate ports.

    Attributes:
        storage: The real-time storage port for saving emergency data.
        coordinator: The coordinator port for reporting emergencies.
    """

    def __init__(
        self, storage: RealTimeStoragePort, coordinator: CoordinatorPort
    ) -> None:
        """Initializes the handler with storage and coordinator services.

        Args:
            storage: The real-time storage port for saving emergency data.
            coordinator: The coordinator port for reporting emergencies.
        """
        super().__init__()
        self.storage = storage
        self.coordinator = coordinator

    @property
    def events(self):
        """Returns the list of events generated by this handler.

        Returns:
            An empty list as this handler doesn't generate events.
        """
        return []

    async def handle(self, request: ReportEmergencyCommand) -> None:
        """Handles the emergency reporting command.

        Args:
            request: The ReportEmergencyCommand containing emergency information.
        """
        emergency = request.to_domain()
        await self.storage.save_emergency(emergency)
        await self.coordinator.report_emergency(emergency)
