import type { CSSProperties } from "react";
import { operatorUiColors as U } from "@/lib/themes/Colors";

export const styles: Record<string, CSSProperties> = {
  container: {
    width: 340,
    borderRight: `1px solid ${U.border}`,
    background: U.surface,
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
  },
  header: {
    padding: "12px 16px",
    borderBottom: `1px solid ${U.border}`,
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  backBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: U.primary,
    display: "flex",
    padding: 4,
  },
  headerTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: U.text,
  },
  body: {
    flex: 1,
    overflowY: "auto",
    padding: 16,
  },
  section: { marginBottom: 16 },
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    color: U.textTer,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  sectionValue: {
    fontSize: 13,
    color: U.text,
    lineHeight: 1.6,
  },
  statusBadge: {
    display: "inline-block",
    padding: "3px 12px",
    borderRadius: 6,
    fontSize: 12,
    fontWeight: 700,
  },
  priorityBadge: {
    display: "inline-block",
    padding: "4px 14px",
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 700,
  },
  locationRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 6,
  },
  paramedicCard: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: U.bg,
    padding: 10,
    borderRadius: 8,
  },
  paramedicAvatar: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: U.primary,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
    fontWeight: 700,
  },
  paramedicName: { fontSize: 13, fontWeight: 600 },
  paramedicEta: { fontSize: 11, color: U.textSec },
  notesBox: {
    border: `1.5px dashed ${U.border}`,
    borderRadius: 8,
    padding: 10,
    minHeight: 60,
    fontSize: 12,
    color: U.textTer,
    fontStyle: "italic" as const,
  },
  actions: {
    padding: "12px 16px",
    borderTop: `1px solid ${U.border}`,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
};
