import type { CSSProperties } from "react";
import { operatorUiColors as U } from "@/lib/themes/Colors";

export const styles: Record<string, CSSProperties> = {
  card: {
    display: "block",
    width: "100%",
    textAlign: "left",
    border: `1.5px solid ${U.border}`,
    borderRadius: 8,
    padding: "12px 14px",
    background: U.surface,
    cursor: "pointer",
    transition: "all .15s",
    marginBottom: 6,
    font: "inherit",
    position: "relative",
  },
  cardSelected: {
    borderColor: U.primary,
    background: U.primaryLight,
  },
  topRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  alertId: {
    fontSize: 11,
    color: U.textTer,
    fontWeight: 600,
    letterSpacing: 0.5,
  },
  time: {
    fontSize: 11,
    color: U.textTer,
  },
  patientName: {
    fontSize: 14,
    fontWeight: 600,
    color: U.text,
    marginBottom: 4,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  addressRow: {
    fontSize: 12,
    color: U.textSec,
    marginBottom: 8,
    display: "flex",
    alignItems: "center",
    gap: 4,
  },
  bottomRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  statusBadge: {
    fontSize: 11,
    fontWeight: 600,
    padding: "2px 10px",
    borderRadius: 4,
  },
  minutesAgo: {
    fontSize: 11,
    color: U.textTer,
  },
  takeBtn: {
    position: "absolute",
    top: "50%",
    right: 10,
    transform: "translateY(-50%)",
    width: 28,
    height: 28,
    borderRadius: "50%",
    background: U.primary,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 700,
    boxShadow: "0 2px 6px rgba(37,121,133,.3)",
    zIndex: 2,
    border: "none",
    padding: 0,
    fontFamily: "inherit",
  },
  takeBtnSubtle: {
    position: "absolute",
    top: "50%",
    right: 10,
    transform: "translateY(-50%)",
    width: 24,
    height: 24,
    borderRadius: "50%",
    background: U.bg,
    color: U.textTer,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    zIndex: 2,
    border: "none",
    padding: 0,
    fontFamily: "inherit",
  },
};
