import type { CSSProperties } from "react";
import { operatorUiColors as U } from "@/lib/themes/Colors";

export const styles: Record<string, CSSProperties> = {
  panel: {
    position: "absolute",
    top: 16,
    left: 16,
    width: 248,
    maxHeight: "calc(100% - 32px)",
    background: U.surface,
    border: `1px solid ${U.border}`,
    borderRadius: 10,
    boxShadow: "0 6px 20px rgba(15,23,42,0.08)",
    display: "flex",
    flexDirection: "column",
    zIndex: 5,
    overflow: "hidden",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 12px",
    borderBottom: `1px solid ${U.borderLight}`,
  },
  headerTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: U.text,
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  headerCount: {
    fontSize: 11,
    fontWeight: 600,
    color: U.textTer,
    fontVariantNumeric: "tabular-nums",
  },
  toggleBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: U.textSec,
    padding: 4,
    borderRadius: 6,
    fontSize: 16,
    lineHeight: 1,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  list: {
    padding: 8,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  item: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: "8px 10px",
    border: `1px solid ${U.border}`,
    borderLeftWidth: 3,
    borderRadius: 6,
    background: U.surface,
    cursor: "pointer",
    textAlign: "left",
    font: "inherit",
    transition: "background .12s, border-color .12s",
  },
  itemActive: {
    background: U.primaryLight,
    borderColor: U.primary,
  },
  itemTopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
  },
  itemId: {
    fontSize: 11,
    fontWeight: 700,
    color: U.text,
    letterSpacing: 0.4,
    fontVariantNumeric: "tabular-nums",
  },
  itemTime: {
    fontSize: 10,
    color: U.textTer,
    fontVariantNumeric: "tabular-nums",
  },
  itemStatus: {
    display: "inline-block",
    fontSize: 10,
    fontWeight: 700,
    padding: "1px 6px",
    borderRadius: 3,
    alignSelf: "flex-start",
  },
  fab: {
    position: "absolute",
    top: 16,
    left: 16,
    width: 44,
    height: 44,
    borderRadius: "50%",
    background: U.primary,
    color: "#fff",
    border: "none",
    cursor: "pointer",
    boxShadow: "0 4px 12px rgba(37,121,133,0.35)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 5,
    fontWeight: 700,
    fontSize: 14,
    fontVariantNumeric: "tabular-nums",
  },
  fabBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    padding: "0 5px",
    borderRadius: 9,
    background: U.error,
    color: "#fff",
    fontSize: 10,
    fontWeight: 700,
    lineHeight: "18px",
    textAlign: "center",
    border: `2px solid ${U.surface}`,
    fontVariantNumeric: "tabular-nums",
  },
};
