[project]
name = "historical-api"
version = "0.1.0"
description = "A REST API to the historical register system"
authors = [
    {name = "Fernando González Rivero",email = "fernando.gonzalezr@upb.edu.co"}
]
readme = "README.md"
requires-python = "<4,>=3.12"
dynamic = ["dependencies"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
fastapi = {extras = ["standard"], version = "^0.136.0"}
core = {path = "../core"}
docker-discovery = {path = "../docker-service-discovery"}
sie-auth = {path = "../auth"}
numpy = "^2.4.4"
