services:
  dragonflyDb:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379"
  coordinator:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    ports:
      - "8000:8000"
  paramedic-location-updater:
    build:
      context: .
      dockerfile: paramedic-location-updater/Dockerfile
    ports:
      - "8001:8000"
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    ports:
      - "8002:8000"
