services:
  dragonflyDb:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379"
  coordinator:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    ports:
      - "8000:8000"
